# == Schema Information
#
# Table name: rendered_pages
#
#  id         :integer          not null, primary key
#  user_id    :string           not null
#  name       :string           not null
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RenderedPage < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................

  # validations ...............................................................
  validates :user_id, presence: true
  validates :name, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................

  # public instance methods ...................................................
  def body_fragment
    Nokogiri::HTML.fragment body
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
